name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python requirements (if any)
        run: |
          python -m pip install --upgrade pip numpy scipy pytest numba
          if [ -f artifact/code/requirements.txt ]; then pip install -r artifact/code/requirements.txt; fi

      - name: Cache Lean lake build
        uses: actions/cache@v3
        with:
          path: |
            artifact/proofs/.lake
            artifact/proofs/lake-manifest.json
          key: ${{ runner.os }}-lean-${{ hashFiles('artifact/proofs/lake-manifest.json') }}

      - name: Install Lean toolchain
        run: |
          # leanup installs elan (Lean version manager)
          curl -sSf https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh 